### ISSUE TITLE
Decide settings spec

### ISSUE THREAD

**Issue by yuichielectric** [octodemo/pr-gatekeeper#29]
Originally, I thought it would be a good idea to use the `approvals` part of the Zappr configuration spec by removing some of the unnecessary ones, but when I read their documentation again, I started to think that the spec is complicated.

https://zappr.readthedocs.io/en/latest/setup/

In particular, I find it difficult to distinguish between `from` and `groups`. As I understand it, the users specified in `from` are those who are considered as reviewers, and the users specified in `groups` are the reviewers who must approve. 

```yaml
# just an example how to configure it
approvals:
  pattern: "^(:\\+1:|👍)" # must start with thumbs up
  minimum: 2 # at least two approvals from other people necessary
  ignore: pr_opener # do not count approval from PR opener
  from: # has to be either one of the following
    orgs:
      - zalando
    collaborators: true
    users:
      - prayerslayer
      - mfellner
  groups:
    # mfellner is required approver on every PR
    seniors:
      minimum: 1
      from:
        users:
          - mfellner
```

In the use case we were originally thinking of, it is important to be able to specify people who must be approved, such as those specified in `groups`, so I think it would be a good idea to implement this specification first. However, even in that case, I think the name `groups` is confusing, so it would be better to think of another name.

@dchomh @rerwinx I would appreciate your thoughts on this!
